import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {Bell,Home,Users,BarChart3,Menu,X,ChevronDown,ChevronRight,Send,Plus,Cloud,Settings,Tags,Code2,CreditCard,HelpCircle,ShieldCheck,Database,Smartphone,RefreshCw,Sparkles,Activity,Zap,LogOut,Search,Check,Download,Lock,Globe,Copy} from "lucide-react";
import "./styles.css";
import {authReady,authHeader,registerPush,listenForMessages,auth} from "./firebase";
import {signOut} from "firebase/auth";

const groups=[["Workspace",[["Dashboard",Home],["Applications",Smartphone],["Notifications",Bell]]],["Audience",[["Subscribers",Users],["Segments",Users],["Tags",Tags]]],["Analytics",[["Overview",BarChart3],["Notification Performance",Activity]]],["Developer",[["API",Code2],["SDK",Code2],["Webhooks",Code2],["Integrations",Code2]]],["Account",[["Billing",CreditCard],["Settings",Settings]]],["Data",[["Backup & Restore",Cloud],["Export Data",Database]]],["Support",[["Help Center",HelpCircle],["Contact Support",HelpCircle]]]];
const plans=[{id:"free",name:"Free",price:"₦0",usd:"$0",features:["1,000 subscribers","Browser push notifications","7-day history"]},{id:"starter",name:"Starter",price:"₦5,000",usd:"$3",features:["5,000 subscribers","Audience tags","30-day history"]},{id:"pro",name:"Pro",price:"₦12,000",usd:"$7",features:["25,000 subscribers","Audience tags","90-day history"]},{id:"business",name:"Business",price:"₦25,000",usd:"$15",features:["100,000 subscribers","Audience tags","365-day history"]}];

function apiFetch(action,options={}){const query=String(action).includes("&")?String(action):encodeURIComponent(action);return authHeader().then(h=>fetch(`/api?action=${query}`,{...options,headers:{"Content-Type":"application/json",...h,...(options.headers||{})}}));}
function App(){
 const parsePage=()=>{const raw=decodeURIComponent(location.hash.slice(1)||""); if(raw)return raw.replaceAll("-"," "); if(new URLSearchParams(location.search).get("reference"))return "Billing"; return "Dashboard"};
 const [page,setPage]=useState(parsePage),[drawer,setDrawer]=useState(false),[compose,setCompose]=useState(false),[dark,setDark]=useState(localStorage.theme!=="light"),[toast,setToast]=useState(""),[loading,setLoading]=useState(true),[data,setData]=useState({subscribers:0,notifications:0,recent:[],subscription:{}}),[authError,setAuthError]=useState(""),[search,setSearch]=useState("");
 const notify=m=>{setToast(m);setTimeout(()=>setToast(""),2600)};
 const refresh=async()=>{try{const r=await apiFetch("dashboard");const d=await r.json();if(!r.ok)throw Error(d.error);setData(d)}catch(e){notify(e.message)}};
 useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light";localStorage.theme=dark?"dark":"light"},[dark]);
 useEffect(()=>{(async()=>{try{await authReady;await refresh();setLoading(false)}catch(e){setAuthError(e.message);setLoading(false)}})();navigator.serviceWorker?.register("/firebase-messaging-sw.js").catch(()=>{})},[]);
 useEffect(()=>{const h=()=>setPage(parsePage());addEventListener("hashchange",h);return()=>removeEventListener("hashchange",h)},[]);
 useEffect(()=>{let off;listenForMessages?.(p=>notify(`${p?.notification?.title||"Notification"}: ${p?.notification?.body||""}`)).then(x=>off=x).catch(()=>{});return()=>off?.()},[]);
 const nav=p=>{setPage(p);location.hash=encodeURIComponent(p.replaceAll(" ","-"));setDrawer(false);setSearch("")};
 const visibleRecent=useMemo(()=>data.recent.filter(x=>!search||`${x.title} ${x.message||""} ${x.audience||""}`.toLowerCase().includes(search.toLowerCase())),[data.recent,search]);
 if(authError)return <div className="app"><main className="main"><div className="content"><section className="page panel"><div className="eyebrow"><ShieldCheck size={13}/>Setup required</div><h1>Couldn't connect to your workspace</h1><p>{authError}</p><p>If this persists, confirm Anonymous authentication is enabled for the Firebase project, then reload WyNotify.</p><button className="primary" onClick={()=>location.reload()}><RefreshCw size={16}/>Retry</button></section></div></main></div>;
 if(loading)return <div className="app"><main className="main"><div className="content"><section className="page panel"><div className="eyebrow"><Sparkles size={13}/>WyNotify v4</div><h1>Loading workspace…</h1><p>Connecting your secure workspace.</p></section></div></main></div>;
 return <div className="app"><aside className={`sidebar ${drawer?"open":""}`}><div className="brand"><span className="logo"><Bell size={18}/></span><b>WyNotify</b><button className="icon mobile" onClick={()=>setDrawer(false)}><X/></button></div><div className="workspace"><span>W</span><div><b>My Workspace</b><small>{data.subscription?.plan?`${data.subscription.plan} plan`:`Free plan`}</small></div><ChevronDown size={15}/></div><div className="search"><Search size={14}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search notifications" onKeyDown={e=>e.key==="Enter"&&nav("Notifications")}/></div><nav>{groups.map(([g,items])=><Group key={g} title={g} items={items} page={page} nav={nav}/>)}</nav><button className="navItem" onClick={async()=>{await signOut(auth);location.reload()}}><LogOut size={16}/>Sign out</button></aside>{drawer&&<div className="backdrop" onClick={()=>setDrawer(false)}/>}<main className="main"><header><button className="icon mobile" onClick={()=>setDrawer(true)}><Menu/></button><div className="crumb">Workspace <ChevronRight size={13}/><b>{page}</b></div><div className="actions"><button className="icon" onClick={refresh}><RefreshCw size={17}/></button><button className="icon" onClick={()=>setDark(!dark)}>{dark?"☀":"☾"}</button></div></header><div className="content">{page==="Dashboard"?<Dashboard data={{...data,recent:visibleRecent}} send={()=>setCompose(true)} nav={nav}/>:page==="Billing"?<Billing notify={notify} data={data} refresh={refresh}/>:page==="Applications"?<Applications notify={notify}/>:page==="Notifications"?<Notifications data={{...data,recent:visibleRecent}} send={()=>setCompose(true)} refresh={refresh}/>:page==="Subscribers"?<Subscribers data={data} notify={notify}/>:page==="Backup & Restore"?<Backup data={data} notify={notify}/>:page==="Export Data"?<ExportData data={data} notify={notify}/>:page==="Settings"?<SettingsPage dark={dark} setDark={setDark}/>:<InfoPage page={page} nav={nav}/>}</div><button className="fab mobile" onClick={()=>setCompose(true)}><Plus/></button><Bottom page={page} nav={nav} menu={()=>setDrawer(true)}/></main>{compose&&<Composer close={()=>setCompose(false)} sent={async payload=>{try{const r=await apiFetch("send",{method:"POST",body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw Error(d.error);setCompose(false);notify(`Sent to ${d.sent} device${d.sent===1?"":"s"}.`);refresh()}catch(e){notify(e.message)}}}/>} {toast&&<div className="toast"><ShieldCheck size={16}/>{toast}</div>}</div>
}
function Group({title,items,page,nav}){const [open,setOpen]=useState(true);return <section className="group"><button className="groupTitle" onClick={()=>setOpen(!open)}>{title}<ChevronDown className={open?"":"rot"}/></button>{open&&items.map(([n,I])=><button className={`navItem ${page===n?"active":""}`} onClick={()=>nav(n)} key={n}><I size={16}/><span>{n}</span></button>)}</section>}
function Dashboard({data,send,nav}){const delivered=data.recent.reduce((a,x)=>a+(Number(x.successCount)||0),0); const attempted=data.recent.reduce((a,x)=>a+(Number(x.count)||0),0); const delivery=attempted?`${Math.round(delivered/attempted*100)}%`:"—"; const stats=[["Subscribers",data.subscribers,Users],["Notifications",data.notifications,Bell],["Delivery",delivery,Zap],["Plan",data.subscription?.plan||"Free",CreditCard]];
 const hasSubscriber=data.subscribers>0, hasSent=data.notifications>0, hasPaidPlan=(data.subscription?.plan||"free")!=="free";
 const steps=[["Register your first device (Applications)",hasSubscriber,()=>nav("Applications")],["Send a test notification",hasSent,send],["Upgrade when you need more capacity",hasPaidPlan,()=>nav("Billing")]];
 const done=steps.filter(s=>s[1]).length;
 return <><section className="hero"><div><div className="eyebrow"><Sparkles size={13}/>Notification command center</div><h1>Good morning</h1><p>Send real browser push notifications from your workspace.</p></div><button className="primary desktop" onClick={send}><Send size={16}/>Send notification</button></section><div className="stats">{stats.map(([n,v,I])=><div className="stat" key={n}><div>{n}<span><I size={15}/></span></div><strong>{v}</strong><small>Live workspace data</small></div>)}</div><div className="cols"><section className="panel"><Head title="Recent notifications" action="View all" onClick={()=>nav("Notifications")}/>{data.recent.length?data.recent.slice(0,5).map(x=><Row key={x.id} t={x.title} a={x.audience} s={x.status} c={`${x.successCount||0}/${x.count||0}`}/>):<Empty text="No notifications yet. Send your first message." action="Send notification" onClick={send}/>}</section><section className="panel"><Head title="Quick actions"/><div className="quick"><button onClick={send}><Send/>Send notification<ChevronRight/></button><button onClick={()=>nav("Applications")}><Smartphone/>Register a device<ChevronRight/></button><button onClick={()=>nav("Subscribers")}><Users/>View subscribers<ChevronRight/></button><button onClick={()=>nav("Billing")}><CreditCard/>Upgrade plan<ChevronRight/></button></div></section></div><section className="panel"><Head title="Get started" action={`${done}/${steps.length} steps`}/>{steps.map(([x,isDone,onClick])=><div className="check" key={x} onClick={isDone?undefined:onClick} style={{cursor:isDone?"default":"pointer"}}><span className={isDone?"done":""}>{isDone?"✓":""}</span>{x}<ChevronRight/></div>)}</section></>}
function Head({title,action,onClick}){return <div className="head"><div><h2>{title}</h2><p>Live workspace controls</p></div>{action&&<button className="link" onClick={onClick}>{action}</button>}</div>}
function Row({t,a,s,c}){return <div className="row"><span className="mini"><Bell size={15}/></span><div><b>{t}</b><small>{a||"All subscribers"}</small></div><aside><label className={String(s||"").toLowerCase()}>{s||"sent"}</label><small>{c}</small></aside></div>}
function Empty({text,action,onClick}){return <div className="empty"><p>{text}</p>{action&&<button className="primary" onClick={onClick}><Send size={15}/>{action}</button>}</div>}
function Applications({notify}){const [busy,setBusy]=useState(false),[registered,setRegistered]=useState(false);const enable=async()=>{setBusy(true);try{await registerPush();setRegistered(true);notify("This browser is now registered for push notifications.")}catch(e){notify(e.message)}finally{setBusy(false)}};return <section className="page"><div className="eyebrow"><Smartphone size={13}/>Workspace / Applications</div><h1>Applications</h1><p>Register this browser as a test device for this workspace. Customer apps can register their own devices with the public workspace key shown under Subscribers.</p><div className="panel drive"><div className="logo"><Bell size={20}/></div><div><b>Browser application</b><small>FCM Web Push registration</small></div><button className="primary" disabled={busy||registered} onClick={enable}>{busy?"Registering…":registered?"Registered":"Enable notifications"}</button></div><div className="notice"><ShieldCheck size={17}/>This uses your browser's built-in push notifications, so it only works over a secure (HTTPS) connection.</div></section>}
function Notifications({data,send,refresh}){return <section className="page"><div className="eyebrow"><Bell size={13}/>Workspace / Notifications</div><div className="pageTitle"><div><h1>Notifications</h1><p>Every message you've sent appears here, along with how many devices it reached.</p></div><button className="primary" onClick={send}><Send size={16}/>Send notification</button></div><div className="panel">{data.recent.length?data.recent.map(x=><Row key={x.id} t={x.title} a={x.audience} s={x.status} c={`${x.successCount||0} sent · ${x.failureCount||0} failed`}/>):<Empty text="No notifications yet." action="Send notification" onClick={send}/>}<button className="secondary" onClick={refresh}><RefreshCw size={15}/>Refresh</button></div></section>}
function Subscribers({data,notify}){const [copied,setCopied]=useState("");const key=data.registration?.workspaceKey||"";const endpoint=data.registration?.endpoint||"/api?action=registerDevice";const snippet=`fetch("${endpoint}", {
  method: "POST",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify({
    workspaceKey: "${key}",
    token: fcmToken, // the token your app got from Firebase Cloud Messaging
    subscriberType: "customers", // e.g. "customers", "vip" — used to target sends
    tags: ["new-users"] // optional labels for finer targeting
  })
})`;const fileContents=`// WyNotify integration — drop this file into your website or app
// and call registerForNotifications(fcmToken) once you have a
// Firebase Cloud Messaging token for the current visitor/user.
//
// Your workspace registration key is already filled in below.
// Treat it like a public key: it only allows registering devices,
// nothing else.

const WYNOTIFY_ENDPOINT = "${endpoint}";
const WYNOTIFY_WORKSPACE_KEY = "${key}";

export async function registerForNotifications(fcmToken, { subscriberType = "customers", tags = [] } = {}) {
  const res = await fetch(WYNOTIFY_ENDPOINT, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      workspaceKey: WYNOTIFY_WORKSPACE_KEY,
      token: fcmToken,
      subscriberType,
      tags,
    }),
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data.error || "Could not register this device for notifications.");
  return data;
}
`;const copy=async(v,label)=>{try{await navigator.clipboard.writeText(v);setCopied(label);notify(`${label} copied`)}catch{notify("Clipboard access is unavailable")}};const downloadFile=()=>{const blob=new Blob([fileContents],{type:"text/javascript"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="wynotify-register.js";a.click();URL.revokeObjectURL(a.href);notify("Integration file downloaded")};return <section className="page"><div className="eyebrow"><Users size={13}/>Audience / Subscribers</div><h1>Subscribers</h1><p>Active customer browser/device registrations attached to this workspace.</p><div className="stats"><div className="stat"><div>Active subscribers<span><Smartphone size={15}/></span></div><strong>{data.subscribers}</strong><small>{data.subscription?.plan||"Free"} plan capacity</small></div></div><div className="panel"><h2>Connect your customer app</h2><p>Your customers don't need a WyNotify account. Your website or app asks their browser for a Firebase Cloud Messaging token, then sends that token to the endpoint below along with your workspace key. That's it — they're subscribed.</p><label>Workspace registration key<input readOnly value={key}/></label><button className="secondary" onClick={()=>copy(key,"Registration key")}><Copy size={15}/>Copy key</button><label>Registration endpoint<input readOnly value={endpoint}/></label><button className="secondary" onClick={()=>copy(endpoint,"Endpoint")}><Copy size={15}/>Copy endpoint</button><p><small>Example call your developer can use directly:</small></p><pre className="codeBlock">{snippet}</pre><button className="secondary" onClick={()=>copy(snippet,"SDK snippet")}><Code2 size={15}/>Copy snippet</button><button className="secondary" onClick={downloadFile}><Download size={15}/>Download integration file (.js)</button>{copied&&<small>Copied: {copied}</small>}</div></section>}
function Billing({notify,data,refresh}){const [email,setEmail]=useState(""),[phone,setPhone]=useState(""),[loading,setLoading]=useState(""),[status,setStatus]=useState("");useEffect(()=>{const q=new URLSearchParams(location.search);const ref=q.get("reference");if(!ref)return;(async()=>{setStatus("Verifying payment…");try{const r=await apiFetch(`verifyPayment&reference=${encodeURIComponent(ref)}`);const d=await r.json();if(!r.ok)throw Error(d.error);setStatus(d.status==="succeeded"?`Payment confirmed — ${d.plan} is active.`:`Payment status: ${d.status}`);await refresh();history.replaceState({},"",location.pathname+"#Billing");}catch(e){setStatus(e.message)}})()},[]);const pay=async p=>{if(p.id==="free")return; if(!email.trim())return notify("Enter your billing email first.");setLoading(p.id);try{const r=await apiFetch("opay",{method:"POST",body:JSON.stringify({email,phone,name:email.split("@")[0],amount:Number(p.price.replace(/[₦,]/g,"")),currency:"NGN",plan:p.id})});const d=await r.json();if(!r.ok)throw Error(d.error);const link=d.data?.data?.next_action?.redirect_url?.url||d.data?.next_action?.redirect_url||d.data?.redirect_url;if(!link)throw Error("Flutterwave did not return a payment redirect.");location.href=link}catch(e){notify(e.message)}finally{setLoading("")}};return <section className="page"><div className="eyebrow"><CreditCard size={13}/>Account / Billing</div><h1>Simple pricing</h1><p>NGN checkout through Flutterwave v4. Notifications themselves are not metered.</p>{status&&<div className="notice"><ShieldCheck size={17}/>{status}</div>}<div className="billingTop panel"><div><Lock size={17}/><b>Secure server-side billing</b><small>We never see or store your card details.</small></div><div className="billingForm"><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Billing email" type="email"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone (optional)"/></div></div><div className="plans">{plans.map(p=><div className={`plan ${p.id==="pro"?"featured":""}`} key={p.id}>{p.id==="pro"&&<span className="popular">Popular</span>}<h2>{p.name}</h2><strong>{p.price}<small>/month</small></strong><em>{p.usd}/month reference</em><div>{p.features.map(f=><span key={f}><Check size={14}/>{f}</span>)}</div><button className={p.id==="free"?"secondary":"primary"} disabled={!!loading} onClick={()=>pay(p)}>{loading===p.id?"Starting…":p.id==="free"?(data.subscription?.plan||"free")==="free"?"Current plan":"Free":"Continue to payment"}</button></div>)}</div></section>}
function Composer({close,sent}){const [t,setT]=useState(""),[m,setM]=useState(""),[audience,setAudience]=useState("all");return <div className="modal" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="composer"><div className="composerHead"><div><div className="eyebrow"><Send size={13}/>New notification</div><h2>Send a message</h2></div><button className="icon" onClick={close}><X/></button></div><label>Title<input autoFocus value={t} onChange={e=>setT(e.target.value)} placeholder="Your notification title"/></label><label>Message<textarea value={m} onChange={e=>setM(e.target.value)} placeholder="Write something useful…" rows="4"/></label><label>Audience<select value={audience} onChange={e=>setAudience(e.target.value)}><option value="all">All subscribers</option><option value="customers">Customers</option><option value="new-users">New users</option><option value="vip">VIP</option></select></label><div className="preview"><small>PREVIEW</small><div><span className="logo"><Bell size={14}/></span><article><b>{t||"Notification title"}</b><p>{m||"Your notification will appear here."}</p></article></div></div><footer><button className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={!t.trim()||!m.trim()} onClick={()=>sent({title:t,message:m,audience})}><Send size={16}/>Send now</button></footer></div></div>}
function Backup({data,notify}){const downloadBackup=()=>{const blob=new Blob([JSON.stringify({version:4,exportedAt:new Date().toISOString(),workspace:{subscription:data.subscription||{},recent:data.recent||[]}},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`wynotify-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);notify("Backup downloaded");};return <section className="page panel"><div className="eyebrow"><Cloud size={13}/>Data</div><h1>Backup & Restore</h1><p>Export a safe workspace snapshot. Secrets and device push tokens are never placed in the backup.</p><div className="backupGrid"><div><b>Backup now</b><p>Download a portable JSON snapshot of workspace metadata and recent notification history.</p><button className="primary" onClick={downloadBackup}><Download size={16}/>Download backup</button></div><div><b>Validate backup</b><p>Select a WyNotify JSON backup to validate its structure before handing it to a server-side restore process.</p><input type="file" accept="application/json,.json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{const x=JSON.parse(await f.text());if(x?.version!==4||!x?.workspace)throw new Error("This is not a compatible WyNotify v4 backup.");notify("Backup is valid. No secrets or device tokens will be imported.")}catch(err){notify(err.message||"Invalid backup file.")}}}/></div></div></section>}
function ExportData({data,notify}){const exp=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="wynotify-data.json";a.click();URL.revokeObjectURL(a.href);notify("Data exported")};return <section className="page panel"><div className="eyebrow"><Database size={13}/>Data</div><h1>Export Data</h1><p>Export the currently loaded workspace data as JSON.</p><button className="primary" onClick={exp}><Download size={16}/>Export JSON</button></section>}
function SettingsPage({dark,setDark}){return <section className="page panel"><div className="eyebrow"><Settings size={13}/>Account / Settings</div><h1>Settings</h1><div className="setting"><div><b>Dark mode</b><small>Use the low-glare interface.</small></div><button className="secondary" onClick={()=>setDark(!dark)}>{dark?"Enabled":"Disabled"}</button></div></section>}
function InfoPage({page,nav}){const map={Segments:"A segment is just a group of subscribers who share a subscriberType or tag — for example everyone tagged \"vip\". Set these when your app registers a device, then target them when you send.",Tags:"Tags are labels you attach to a subscriber when they register (e.g. \"new-user\", \"vip\"). Use them later to send a notification to just that group instead of everyone.",Overview:"These numbers come from the notifications you've actually sent — there's nothing to configure. Tracking whether a customer opened a notification isn't included yet; only send/delivery counts are.","Notification Performance":"Delivery counts reflect how many of your subscribers' devices actually received each notification you've sent.",API:"Your website or app only needs one of these — the first one below — to start collecting subscribers. The rest are used by this dashboard when you send messages or manage billing, and aren't something you need to call yourself.",SDK:"In your own app, use Firebase Cloud Messaging to get a push token for your visitor, then send that token to your registration endpoint (shown under Subscribers) to subscribe them.",Webhooks:"Plan payments are verified and applied automatically — there's nothing for you to set up here.",Integrations:"WyNotify sends push notifications through Firebase Cloud Messaging and takes payments through Flutterwave. Both are already connected for your workspace.","Help Center":"Start with Applications to register a test device, then send yourself a test notification before inviting real subscribers.","Contact Support":"Have a question about your workspace, billing, or getting notifications working on your site? Reach out and we'll help."};return <section className="page panel"><div className="eyebrow"><Globe size={13}/>Workspace</div><h1>{page}</h1><p>{map[page]||"This screen is available in the workspace navigation."}</p>{page==="Contact Support"&&<a className="primary" href={`mailto:${import.meta.env.VITE_SUPPORT_EMAIL||"support@example.com"}`}>Email support</a>}{page==="API"&&<div className="featureList"><div><Check size={15}/>POST /api?action=registerDevice — register a subscriber from your own app (public, no login)</div><div><Check size={15}/>POST /api?action=send — send a notification (used by this dashboard)</div><div><Check size={15}/>GET /api?action=dashboard — load your workspace stats (used by this dashboard)</div><div><Check size={15}/>POST /api?action=opay — start a plan payment (used by Billing)</div><div><Check size={15}/>GET /api?action=verifyPayment — confirm a plan payment (used by Billing)</div></div>}{page==="SDK"&&<button className="primary" onClick={()=>nav("Applications")}><Smartphone size={16}/>Register this browser</button>}</section>}
function Bottom({page,nav,menu}){return <nav className="bottom mobile">{[["Dashboard",Home],["Notifications",Bell],["Subscribers",Users],["Billing",CreditCard]].map(([n,I])=><button className={page===n?"active":""} key={n} onClick={()=>nav(n)}><I/><small>{n}</small></button>)}<button onClick={menu}><Menu/><small>Menu</small></button></nav>}
createRoot(document.getElementById("root")).render(<App/>);
